  version: '3.2'
  services:
    node:
      build: ./
      ports:
        - "80:5001"
      volumes:
        - ./:/usr/src/app
      depends_on:
        - db
      networks:
        - docker_xxx
      environment:
        - DATABASE_HOST=db
    db:
      image: mysql:5
      volumes:
        - ./db_data:/var/lib/mysql
        - ./initmysql.sql:/data/application/init.sql
        - ./initDatabase.sh:/initDatabase.sh
      command: --init-file /data/application/init.sql
      expose:
        - 3306
      environment:
        - MYSQL_ROOT_PASSWORD=root
      networks:
        - docker_xxx
  networks:
    docker_xxx:
      driver: bridge
