  version: '3.3'
  services:
    node:
      build: ./
      ports:
        - "80:5001"
      depends_on:
        - db
      networks:
        - docker_xxx
      environment:
        - DATABASE_HOST=db
    db:
      image: mysql:5
      volumes:
        - ./db_data:/var/lib/mysql
        - ./initmysql.sql:/data/application/init.sql
      command: --init-file /data/application/init.sql
      expose:
        - 3306
      environment:
       - MYSQL_ROOT_PASSWORD='root'
       - MYSQL_DATABASE='qldtoverload'
       - MYSQL_USER='test'
       - MYSQL_PASSWORD='test'
      networks:
        - docker_xxx
  networks:
    docker_xxx:
      driver: bridge
